### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Axer128** [kevinfiol/enhanced-gog#15]
Get this error on every page:
Woops. Enhanced GOG encountered an error. Try another region or click here to try again.

Try again does a little refresh but still not working.

Tested on chrome + tampermonkey.

**Comment by kevinfiol** [comment]
Can you try navigating to a page where this error occurs, open the browser console, and share a screenshot of the errors in the console? I believe the shortcut to open the console on Chrome is Ctrl + Shift + I.

**Comment by Axer128** [comment]
![image](https://github.com/user-attachments/assets/38db08a5-5bc4-49e7-90ba-0894323d7189)

**Comment by Axer128** [comment]
Cleaner one with all other extensions disabled (same results):
![image](https://github.com/user-attachments/assets/dceec4b2-23de-421a-a95e-376c1252ced7)

**Comment by kevinfiol** [comment]
Interesting -- I can't even get the User Script to run on Chromium 126.0.6478.182 using TamperMonkey.

Seems to work fine with ViolentMonkey. Would you mind giving ViolentMonkey or another user-script manager a try? I'm curious if we can isolate this to the user-script manager.

**Comment by kevinfiol** [comment]
@Axer128 Can you please update and let me know if this is still an issue?
