### ISSUE TITLE
Issue with regional price displayed

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [kevinfiol/enhanced-gog#5]
Hi! It seems the script is having issues loading the prices for some regions, loading the price in USD as if it was the regional price instead. And if I go to the ITAD page linked by the script, it shows the correct prices.

Example of such behavior:
[set to show in USD] https://cdn.discordapp.com/attachments/636030269823909921/992855444873814046/unknown.png
[set to show in BRL] https://cdn.discordapp.com/attachments/636030269823909921/992855445058359336/unknown.png
[page on ITAD] https://cdn.discordapp.com/attachments/636030269823909921/992855665984942100/unknown.png

**Comment by kevinfiol** [comment]
Thanks for reporting this. I will investigate this soon.

**Comment by kevinfiol** [comment]
@Auster-South-Anemoi Hi, please update and see version `1.3.2`.

There are now two regions for `br2`: `Brazil 1` and `Brazil 2`. In your case, you would want to select `Brazil 1`.

`Brazil 2` is using the country code `BR2` for which the ITAD API returns USD amounts; for some reason, they are different than what is shown on the mainsite when you select BR > USD. Not sure for the discrepancy, but I am leaving `Brazil 2` for legacy reasons.

**Comment by Auster-South-Anemoi** [comment]
It seems to be working now. Thanks!

**Comment by kevinfiol** [comment]
From GOG Community Thread:
> Hi! It seems the script is having issues loading the prices for some regions, loading the price in USD as if it was the regional price instead. And if I go to the ITAD page linked by the script, it shows the correct prices.

> Example of such behavior:
[set to show in USD] https://cdn.discordapp.com/attachments/636030269823909921/992855444873814046/unknown.png
[set to show in BRL] https://cdn.discordapp.com/attachments/636030269823909921/992855445058359336/unknown.png
[page on ITAD] https://cdn.discordapp.com/attachments/636030269823909921/992855665984942100/unknown.png
