### ISSUE TITLE
[Feature request] Minimize container's height to fit overall under new GOG layout

### ISSUE THREAD

**Issue by DawEdhel** [kevinfiol/enhanced-gog#8]
Gog has added various parts (such as 'Buy now' button, discount's expiration date, etc.) to the product prices' sections since this script's been last updated. Currently on some product pages overall placement pushes some top info of this section under the navbar.

My suggestion is to add some visibility manipulating arrow to hide details part (and leave colored text always-on?), with extra check button if an user wants hidden part to be visible or not on load. Or maybe it's enough to simply adjust elements sizes.

Small notice: on GOG I set browser's scale to 125%, but even on 100% it's at its edge.
As an example: [https://www.gog.com/en/game/travellin_cats_bundle](https://www.gog.com/en/game/travellin_cats_bundle)

**Comment by kevinfiol** [comment]
There is an IsThereAnyDeal API overhaul happening in the next month. I hope to address this along with the API changes in the same week when they happen. Stay tuned. Thanks for reporting this, by the way.

**Comment by kevinfiol** [comment]
@DawEdhel This has been implemented with version `1.5.0`. Ping me if you encounter any issues!
