### ISSUE TITLE
ITAD updated and borked enhanced GOG

### ISSUE THREAD

**Issue by grenhunterz** [kevinfiol/enhanced-gog#9]
Enhanced GOG shows error message on gog games storepages:

Woops. Enhanced GOG encountered an error. Try another region or click here to try again.

**Comment by kevinfiol** [comment]
So it's finally happened. Time to review the new API changes. Thanks for the headsup.

**Comment by kevinfiol** [comment]
Their API docs seem to be in flux right now. The only endpoints I see are v01 versions, and they are returning the `.deprecated` flag: https://itad.docs.apiary.io

I'm also not able to authorize enhanged-gog on the ITAD website at all. I'll have to look more closely, but seems like they're behind in setting up docs for the new API.

**Comment by kevinfiol** [comment]
Bundles endpoint is also totally borked and not returning the specification: https://itad.docs.apiary.io/#reference/game/bundles/get-info-about-where-the-game-was-bundled?console=1

**Comment by DawEdhel** [comment]
They are at the starting point of migration yet, you might go back into the hibernation :)

[https://steamcommunity.com/groups/isthereanydeal/announcements/listing](https://steamcommunity.com/groups/isthereanydeal/announcements/listing)

**Comment by kevinfiol** [comment]
> They are at the starting point of migration yet, you might go back into the hibernation :)
> 
> https://steamcommunity.com/groups/isthereanydeal/announcements/listing

Thanks; I was trying to find a place to keep up to date with the changes.

In the meantime, I've found out I can ignore the `.active` flag when grabbing the game ID as a temporary fix, since the old endpoint is still live. This will probably break soon as well, so I'll keep this issue open. The bundle endpoint is busted so will show `0` at all times at the moment.

**Comment by kevinfiol** [comment]
Aaaand they broke the temp fix. Gonna take a look this weekend.

**Comment by kevinfiol** [comment]
Woohoo, new API is detailed here: https://docs.isthereanydeal.com

I'll get to work on fixing the userscript this week.

**Comment by kevinfiol** [comment]
Hey all, I just pushed up version `1.5.0` which should fix these issues. Please open a new ticket if you encounter any problems.
